CREATE TABLE SUPPLIER (
	S_SUPPKEY 	 INT UNSIGNED,
	S_NAME		CHAR(25),
	S_ADDRESS	VARCHAR(40),
	S_NATIONKEY	INT,
	S_PHONE		CHAR(15),
	S_ACCTBAL	DECIMAL(10,0),
	S_COMMENT	VARCHAR(101),
	PRIMARY KEY(S_SUPPKEY)
) ENGINE = InnoDB
;

